# Environment Configuration
environments:
  - name: acceptance
    provider: ecs-fargate
    loadbalancer:
      hostedzone: shhorsfi.myinstance.com
      name: wordpress-stg
  - name: production
    provider: ecs-fargate
    loadbalancer:
      hostedzone: shhorsfi.myinstance.com
      name: wordpress-prd

# CloudFormation Template Overrides
templates:
  mu-service-wordpress-fargate-acceptance:
    Resources:
      ElbTargetGroup:
        Properties:
          Matcher:
            HttpCode: 200-302
          TargetGroupAttributes:
          - Key: stickiness.enabled
            Value: true
          - Key: stickiness.type
            Value: lb_cookie
          - Key: stickiness.lb_cookie.duration_seconds
            Value: '21600'
      UserUploadBucket:
        Type: AWS::S3::Bucket
  mu-service-wordpress-fargate-production:
    Resources:
      ElbTargetGroup:
        Properties:
          Matcher:
            HttpCode: 200-302
          TargetGroupAttributes:
          - Key: stickiness.enabled
            Value: true
          - Key: stickiness.type
            Value: lb_cookie
          - Key: stickiness.lb_cookie.duration_seconds
            Value: '21600'
      UserUploadBucket:
        Type: AWS::S3::Bucket

# Service Configuration
service:
  port: 80
  healthEndpoint: /
  pathPatterns:
  - /*
  environment:
    WORDPRESS_DB_HOST: ${DatabaseEndpointAddress}:${DatabaseEndpointPort}
    WORDPRESS_DB_USER: ${DatabaseMasterUsername}
    WORDPRESS_DB_PASSWORD: ${DatabaseMasterPassword}
    WORDPRESS_DB_NAME: ${DatabaseName}
    USER_UPLOAD_BUCKET: ${UserUploadBucket}
    USER_UPLOAD_REGION: us-west-2
  pipeline:
    source:
      provider: GitHub
      repo: horsfieldsa/wordpress-fargate
    acceptance:
      disabled: false
      environment: acceptance
    production:
      disabled: true
      environment: production
    notify:
      - shhorsfi@amazon.com
  database:
      name: wordpress
      engine: aurora
      instanceClass: db.t2.small
      iamAuthentication: false
      masterUsername: admin
      allocatedStorage: 10
